### PR TITLE
Update intents.json

### PR DESCRIPTION
**Pull request by aayushsinha0706**
I have updated intents file goodbye and thanks.

### CODE REVIEW

**Review by UjjwalAnand364 — CHANGES_REQUESTED** [review]
Thank you for these, but it would be more helpful if you could add more such phrases. to Greet and Goodbye.

**Comment by aayushsinha0706** [comment]
committed changes

**Comment by UjjwalAnand364** [comment]
Thats good, but can you add more to patterns? The input is quite narrow.

**Comment by aayushsinha0706** [comment]
added changes requested

**Review by UjjwalAnand364 — APPROVED** [review]
Thank you for these changes!

**Pull request merged**
